### PR TITLE
Update NextCloud to 18.0.3 and PHP to 7.3

### PR DESCRIPTION
**Pull request by unixfox**

### CODE REVIEW

**Comment by benyanke** [comment]
Is this working for you? When I try to build it it succeeds, but when I use it to spin up a stack, it fails.

image

Have you gotten this one to work, and if so, can you share a bare minimum docker-compose file with it?

**Comment by unixfox** [comment]
At first, I tried with a fresh install of nextcloud 17 using this docker-compose (from https://github.com/benyanke/docker-nextcloud#docker-compose-file):
```yml
version: '3'

services:
  nextcloud:
    image: benyanke/nextcloud
    depends_on:
      - nextcloud-db           # If using MySQL
    environment:
      - DOMAIN=localhost
      - DB_TYPE=mysql
      - DB_NAME=nextcloud
      - DB_USER=nextcloud
      - DB_PASSWORD=supersecretpassword
      - DB_HOST=nextcloud-db
      - APP_AUTO_UPDATE=1
    volumes:
      - ./data:/data
      - ./config:/config
      - ./apps:/apps2
      - ./themes:/nextcloud/themes
  nextcloud-db:
    image: mariadb:10
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=supersecretpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=supersecretpassword
```

Then I built a Docker image with nextcloud 18 on quay: https://quay.io/repository/unixfox/docker-nextcloud and I switch the image in the docker-compose.
And it worked perfectly, I didn't have any issue while upgrading it.

**Comment by benyanke** [comment]
Thank you! I'll give this a try.

**Comment by benyanke** [comment]
Did that docker-compose file work for you installing 17? It failed for me....
image

**Comment by unixfox** [comment]
Oops, sorry on a fresh install I remember that it is not recommended having `APP_AUTO_UPDATE` enabled if `ADMIN_USER` and `ADMIN_PASSWORD` is not provided due to the fact that the setup is still not finished yet.
So I added both `ADMIN_USER` & `ADMIN_PASSWORD` and it passes without any issue:
```yml
version: '3'

services:
  nextcloud:
    image: benyanke/nextcloud
    depends_on:
      - nextcloud-db           # If using MySQL
    environment:
      - DOMAIN=localhost
      - DB_TYPE=mysql
      - DB_NAME=nextcloud
      - DB_USER=nextcloud
      - DB_PASSWORD=supersecretpassword
      - DB_HOST=nextcloud-db
      - APP_AUTO_UPDATE=1
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin
    volumes:
      - ./data:/data
      - ./config:/config
      - ./apps:/apps2
      - ./themes:/nextcloud/themes
    ports:
      - 8888:8888
  nextcloud-db:
    image: mariadb:10
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=supersecretpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=supersecretpassword
```

After that I switched to my image (`quay.io/unixfox/docker-nextcloud`) and the upgrade worked perfectly.
I made an asciinema for you to see that it works as expected:
[asciicast](https://asciinema.org/a/fdL3Qt2NY83O5dPVLOzdthxMU)

**Comment by unixfox** [comment]
@benyanke any updates here?

**Pull request closed without merging**
